/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssetType = IDL.Variant({
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Time = IDL.Int;
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
  'stakingReward' : IDL.Null,
});
export const TransactionView = IDL.Record({
  'transactionType' : TransactionType,
  'asset' : IDL.Text,
  'date' : Time,
  'fees' : IDL.Opt(IDL.Float64),
  'pricePerUnit' : IDL.Float64,
  'hasOngoingCosts' : IDL.Opt(IDL.Bool),
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
});
export const AssetView = IDL.Record({
  'currentPrice' : IDL.Float64,
  'ticker' : IDL.Text,
  'name' : IDL.Text,
  'assetType' : AssetType,
  'transactions' : IDL.Vec(TransactionView),
});
export const AssetHistoryView = IDL.Record({
  'timestamp' : Time,
  'price' : IDL.Float64,
});
export const StakingRewardView = IDL.Record({
  'date' : Time,
  'quantity' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addAsset' : IDL.Func([IDL.Text, IDL.Text, AssetType, IDL.Float64], [], []),
  'addHistoricalData' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
  'addStakingReward' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
  'addTransaction' : IDL.Func([TransactionView], [], []),
  'deleteAsset' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(AssetView)], ['query']),
  'getAsset' : IDL.Func([IDL.Text], [AssetView], ['query']),
  'getHistoricalData' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssetHistoryView)],
      ['query'],
    ),
  'getStakingRewards' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StakingRewardView)],
      ['query'],
    ),
  'getTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TransactionView)],
      ['query'],
    ),
  'updateAsset' : IDL.Func(
      [IDL.Text, IDL.Text, AssetType, IDL.Float64],
      [],
      [],
    ),
  'updateTransaction' : IDL.Func([IDL.Text, IDL.Nat, TransactionView], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssetType = IDL.Variant({ 'stock' : IDL.Null, 'crypto' : IDL.Null });
  const Time = IDL.Int;
  const TransactionType = IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
    'stakingReward' : IDL.Null,
  });
  const TransactionView = IDL.Record({
    'transactionType' : TransactionType,
    'asset' : IDL.Text,
    'date' : Time,
    'fees' : IDL.Opt(IDL.Float64),
    'pricePerUnit' : IDL.Float64,
    'hasOngoingCosts' : IDL.Opt(IDL.Bool),
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
  });
  const AssetView = IDL.Record({
    'currentPrice' : IDL.Float64,
    'ticker' : IDL.Text,
    'name' : IDL.Text,
    'assetType' : AssetType,
    'transactions' : IDL.Vec(TransactionView),
  });
  const AssetHistoryView = IDL.Record({
    'timestamp' : Time,
    'price' : IDL.Float64,
  });
  const StakingRewardView = IDL.Record({
    'date' : Time,
    'quantity' : IDL.Float64,
  });
  
  return IDL.Service({
    'addAsset' : IDL.Func([IDL.Text, IDL.Text, AssetType, IDL.Float64], [], []),
    'addHistoricalData' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
    'addStakingReward' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
    'addTransaction' : IDL.Func([TransactionView], [], []),
    'deleteAsset' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(AssetView)], ['query']),
    'getAsset' : IDL.Func([IDL.Text], [AssetView], ['query']),
    'getHistoricalData' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssetHistoryView)],
        ['query'],
      ),
    'getStakingRewards' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StakingRewardView)],
        ['query'],
      ),
    'getTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TransactionView)],
        ['query'],
      ),
    'updateAsset' : IDL.Func(
        [IDL.Text, IDL.Text, AssetType, IDL.Float64],
        [],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Text, IDL.Nat, TransactionView],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };