/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssetHistoryView { 'timestamp' : Time, 'price' : number }
export type AssetType = { 'stock' : null } |
  { 'crypto' : null };
export interface AssetView {
  'currentPrice' : number,
  'ticker' : string,
  'name' : string,
  'assetType' : AssetType,
  'transactions' : Array<TransactionView>,
}
export interface StakingRewardView { 'date' : Time, 'quantity' : number }
export type Time = bigint;
export type TransactionType = { 'buy' : null } |
  { 'sell' : null } |
  { 'stakingReward' : null };
export interface TransactionView {
  'transactionType' : TransactionType,
  'asset' : string,
  'date' : Time,
  'fees' : [] | [number],
  'pricePerUnit' : number,
  'hasOngoingCosts' : [] | [boolean],
  'notes' : [] | [string],
  'quantity' : number,
}
export interface _SERVICE {
  'addAsset' : ActorMethod<[string, string, AssetType, number], undefined>,
  'addHistoricalData' : ActorMethod<[string, Time, number], undefined>,
  'addStakingReward' : ActorMethod<[string, Time, number], undefined>,
  'addTransaction' : ActorMethod<[TransactionView], undefined>,
  'deleteAsset' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[string, bigint], undefined>,
  'getAllAssets' : ActorMethod<[], Array<AssetView>>,
  'getAsset' : ActorMethod<[string], AssetView>,
  'getHistoricalData' : ActorMethod<[string], Array<AssetHistoryView>>,
  'getStakingRewards' : ActorMethod<[string], Array<StakingRewardView>>,
  'getTransactions' : ActorMethod<[string], Array<TransactionView>>,
  'updateAsset' : ActorMethod<[string, string, AssetType, number], undefined>,
  'updateTransaction' : ActorMethod<
    [string, bigint, TransactionView],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];