/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AssetType = IDL.Variant({
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Time = IDL.Int;
export const LoanTransactionType = IDL.Variant({
  'interestReceived' : IDL.Null,
  'repaymentReceived' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'dividend' : IDL.Null,
  'sell' : IDL.Null,
  'stakingReward' : IDL.Null,
});
export const TransactionView = IDL.Record({
  'euroValue' : IDL.Opt(IDL.Float64),
  'transactionType' : TransactionType,
  'asset' : IDL.Text,
  'date' : Time,
  'fees' : IDL.Opt(IDL.Float64),
  'pricePerUnit' : IDL.Float64,
  'hasOngoingCosts' : IDL.Opt(IDL.Bool),
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetView = IDL.Record({
  'currentPrice' : IDL.Float64,
  'ticker' : IDL.Text,
  'name' : IDL.Text,
  'assetType' : AssetType,
  'transactions' : IDL.Vec(TransactionView),
});
export const LoanStatus = IDL.Variant({
  'repaid' : IDL.Null,
  'active' : IDL.Null,
  'defaulted' : IDL.Null,
});
export const LoanTransactionView = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : LoanTransactionType,
  'date' : Time,
  'loanId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
});
export const LoanView = IDL.Record({
  'id' : IDL.Nat,
  'status' : LoanStatus,
  'endDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'durationMonths' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'interestRatePercent' : IDL.Opt(IDL.Float64),
  'transactions' : IDL.Vec(LoanTransactionView),
  'loanedAmount' : IDL.Float64,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AssetHistoryView = IDL.Record({
  'timestamp' : Time,
  'price' : IDL.Float64,
});
export const StakingRewardView = IDL.Record({
  'date' : Time,
  'quantity' : IDL.Float64,
});
export const UserSettingsView = IDL.Record({
  'terEntries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'twelveDataApiKey' : IDL.Text,
  'commodityTickers' : IDL.Vec(IDL.Text),
  'ongoingCostsEntries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAsset' : IDL.Func([IDL.Text, IDL.Text, AssetType, IDL.Float64], [], []),
  'addHistoricalData' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
  'addLoan' : IDL.Func(
      [
        IDL.Text,
        Time,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(Time),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addLoanTransaction' : IDL.Func(
      [IDL.Nat, LoanTransactionType, Time, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addStakingReward' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
  'addTransaction' : IDL.Func([TransactionView], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAsset' : IDL.Func([IDL.Text], [], []),
  'deleteLoan' : IDL.Func([IDL.Nat], [], []),
  'deleteLoanTransaction' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(AssetView)], ['query']),
  'getAllLoans' : IDL.Func([], [IDL.Vec(LoanView)], ['query']),
  'getAsset' : IDL.Func([IDL.Text], [AssetView], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistoricalData' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssetHistoryView)],
      ['query'],
    ),
  'getStakingRewards' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StakingRewardView)],
      ['query'],
    ),
  'getTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TransactionView)],
      ['query'],
    ),
  'getUserName' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [UserSettingsView], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserSettings' : IDL.Func([UserSettingsView], [], []),
  'setUserName' : IDL.Func([IDL.Text], [], []),
  'updateAsset' : IDL.Func(
      [IDL.Text, IDL.Text, AssetType, IDL.Float64],
      [],
      [],
    ),
  'updateLoan' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Time,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(Time),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        LoanStatus,
      ],
      [],
      [],
    ),
  'updateTransaction' : IDL.Func([IDL.Text, IDL.Nat, TransactionView], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AssetType = IDL.Variant({ 'stock' : IDL.Null, 'crypto' : IDL.Null });
  const Time = IDL.Int;
  const LoanTransactionType = IDL.Variant({
    'interestReceived' : IDL.Null,
    'repaymentReceived' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'buy' : IDL.Null,
    'dividend' : IDL.Null,
    'sell' : IDL.Null,
    'stakingReward' : IDL.Null,
  });
  const TransactionView = IDL.Record({
    'euroValue' : IDL.Opt(IDL.Float64),
    'transactionType' : TransactionType,
    'asset' : IDL.Text,
    'date' : Time,
    'fees' : IDL.Opt(IDL.Float64),
    'pricePerUnit' : IDL.Float64,
    'hasOngoingCosts' : IDL.Opt(IDL.Bool),
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetView = IDL.Record({
    'currentPrice' : IDL.Float64,
    'ticker' : IDL.Text,
    'name' : IDL.Text,
    'assetType' : AssetType,
    'transactions' : IDL.Vec(TransactionView),
  });
  const LoanStatus = IDL.Variant({
    'repaid' : IDL.Null,
    'active' : IDL.Null,
    'defaulted' : IDL.Null,
  });
  const LoanTransactionView = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : LoanTransactionType,
    'date' : Time,
    'loanId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
  });
  const LoanView = IDL.Record({
    'id' : IDL.Nat,
    'status' : LoanStatus,
    'endDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'durationMonths' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'interestRatePercent' : IDL.Opt(IDL.Float64),
    'transactions' : IDL.Vec(LoanTransactionView),
    'loanedAmount' : IDL.Float64,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AssetHistoryView = IDL.Record({
    'timestamp' : Time,
    'price' : IDL.Float64,
  });
  const StakingRewardView = IDL.Record({
    'date' : Time,
    'quantity' : IDL.Float64,
  });
  const UserSettingsView = IDL.Record({
    'terEntries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'twelveDataApiKey' : IDL.Text,
    'commodityTickers' : IDL.Vec(IDL.Text),
    'ongoingCostsEntries' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAsset' : IDL.Func([IDL.Text, IDL.Text, AssetType, IDL.Float64], [], []),
    'addHistoricalData' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
    'addLoan' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(Time),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addLoanTransaction' : IDL.Func(
        [IDL.Nat, LoanTransactionType, Time, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addStakingReward' : IDL.Func([IDL.Text, Time, IDL.Float64], [], []),
    'addTransaction' : IDL.Func([TransactionView], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAsset' : IDL.Func([IDL.Text], [], []),
    'deleteLoan' : IDL.Func([IDL.Nat], [], []),
    'deleteLoanTransaction' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(AssetView)], ['query']),
    'getAllLoans' : IDL.Func([], [IDL.Vec(LoanView)], ['query']),
    'getAsset' : IDL.Func([IDL.Text], [AssetView], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistoricalData' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssetHistoryView)],
        ['query'],
      ),
    'getStakingRewards' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StakingRewardView)],
        ['query'],
      ),
    'getTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TransactionView)],
        ['query'],
      ),
    'getUserName' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [UserSettingsView], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserSettings' : IDL.Func([UserSettingsView], [], []),
    'setUserName' : IDL.Func([IDL.Text], [], []),
    'updateAsset' : IDL.Func(
        [IDL.Text, IDL.Text, AssetType, IDL.Float64],
        [],
        [],
      ),
    'updateLoan' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Time,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(Time),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          LoanStatus,
        ],
        [],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Text, IDL.Nat, TransactionView],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };