/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AssetView {
    currentPrice: number;
    ticker: string;
    name: string;
    assetType: AssetType;
    transactions: Array<TransactionView>;
}
export type Time = bigint;
export interface AssetHistoryView {
    timestamp: Time;
    price: number;
}
export interface StakingRewardView {
    date: Time;
    quantity: number;
}
export interface TransactionView {
    transactionType: TransactionType;
    asset: string;
    date: Time;
    fees?: number;
    pricePerUnit: number;
    hasOngoingCosts?: boolean;
    notes?: string;
    quantity: number;
}
export enum AssetType {
    stock = "stock",
    crypto = "crypto"
}
export enum TransactionType {
    buy = "buy",
    sell = "sell",
    stakingReward = "stakingReward"
}
export interface backendInterface {
    addAsset(name: string, ticker: string, assetType: AssetType, currentPrice: number): Promise<void>;
    addHistoricalData(asset: string, timestamp: Time, price: number): Promise<void>;
    addStakingReward(asset: string, date: Time, quantity: number): Promise<void>;
    addTransaction(transaction: TransactionView): Promise<void>;
    deleteAsset(ticker: string): Promise<void>;
    deleteTransaction(ticker: string, index: bigint): Promise<void>;
    getAllAssets(): Promise<Array<AssetView>>;
    getAsset(ticker: string): Promise<AssetView>;
    getHistoricalData(asset: string): Promise<Array<AssetHistoryView>>;
    getStakingRewards(asset: string): Promise<Array<StakingRewardView>>;
    getTransactions(asset: string): Promise<Array<TransactionView>>;
    updateAsset(ticker: string, name: string, assetType: AssetType, currentPrice: number): Promise<void>;
    updateTransaction(ticker: string, index: bigint, transaction: TransactionView): Promise<void>;
}
import type { AssetType as _AssetType, AssetView as _AssetView, Time as _Time, TransactionType as _TransactionType, TransactionView as _TransactionView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAsset(arg0: string, arg1: string, arg2: AssetType, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAsset(arg0, arg1, to_candid_AssetType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAsset(arg0, arg1, to_candid_AssetType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addHistoricalData(arg0: string, arg1: Time, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHistoricalData(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHistoricalData(arg0, arg1, arg2);
            return result;
        }
    }
    async addStakingReward(arg0: string, arg1: Time, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStakingReward(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStakingReward(arg0, arg1, arg2);
            return result;
        }
    }
    async addTransaction(arg0: TransactionView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TransactionView_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TransactionView_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAsset(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0, arg1);
            return result;
        }
    }
    async getAllAssets(): Promise<Array<AssetView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAsset(arg0: string): Promise<AssetView> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_AssetView_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_AssetView_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoricalData(arg0: string): Promise<Array<AssetHistoryView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalData(arg0);
            return result;
        }
    }
    async getStakingRewards(arg0: string): Promise<Array<StakingRewardView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStakingRewards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStakingRewards(arg0);
            return result;
        }
    }
    async getTransactions(arg0: string): Promise<Array<TransactionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAsset(arg0: string, arg1: string, arg2: AssetType, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, arg1, to_candid_AssetType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, arg1, to_candid_AssetType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateTransaction(arg0: string, arg1: bigint, arg2: TransactionView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, arg1, to_candid_TransactionView_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, arg1, to_candid_TransactionView_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_AssetType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetType): AssetType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AssetView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssetView): AssetView {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionView): TransactionView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    asset: string;
    date: _Time;
    fees: [] | [number];
    pricePerUnit: number;
    hasOngoingCosts: [] | [boolean];
    notes: [] | [string];
    quantity: number;
}): {
    transactionType: TransactionType;
    asset: string;
    date: Time;
    fees?: number;
    pricePerUnit: number;
    hasOngoingCosts?: boolean;
    notes?: string;
    quantity: number;
} {
    return {
        transactionType: from_candid_TransactionType_n15(_uploadFile, _downloadFile, value.transactionType),
        asset: value.asset,
        date: value.date,
        fees: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.fees)),
        pricePerUnit: value.pricePerUnit,
        hasOngoingCosts: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.hasOngoingCosts)),
        notes: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    ticker: string;
    name: string;
    assetType: _AssetType;
    transactions: Array<_TransactionView>;
}): {
    currentPrice: number;
    ticker: string;
    name: string;
    assetType: AssetType;
    transactions: Array<TransactionView>;
} {
    return {
        currentPrice: value.currentPrice,
        ticker: value.ticker,
        name: value.name,
        assetType: from_candid_AssetType_n10(_uploadFile, _downloadFile, value.assetType),
        transactions: from_candid_vec_n12(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stock: null;
} | {
    crypto: null;
}): AssetType {
    return "stock" in value ? AssetType.stock : "crypto" in value ? AssetType.crypto : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
} | {
    stakingReward: null;
}): TransactionType {
    return "buy" in value ? TransactionType.buy : "sell" in value ? TransactionType.sell : "stakingReward" in value ? TransactionType.stakingReward : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionView>): Array<TransactionView> {
    return value.map((x)=>from_candid_TransactionView_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssetView>): Array<AssetView> {
    return value.map((x)=>from_candid_AssetView_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AssetType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): _AssetType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionView): _TransactionView {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: TransactionType;
    asset: string;
    date: Time;
    fees?: number;
    pricePerUnit: number;
    hasOngoingCosts?: boolean;
    notes?: string;
    quantity: number;
}): {
    transactionType: _TransactionType;
    asset: string;
    date: _Time;
    fees: [] | [number];
    pricePerUnit: number;
    hasOngoingCosts: [] | [boolean];
    notes: [] | [string];
    quantity: number;
} {
    return {
        transactionType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.transactionType),
        asset: value.asset,
        date: value.date,
        fees: value.fees ? candid_some(value.fees) : candid_none(),
        pricePerUnit: value.pricePerUnit,
        hasOngoingCosts: value.hasOngoingCosts ? candid_some(value.hasOngoingCosts) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetType): {
    stock: null;
} | {
    crypto: null;
} {
    return value == AssetType.stock ? {
        stock: null
    } : value == AssetType.crypto ? {
        crypto: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    buy: null;
} | {
    sell: null;
} | {
    stakingReward: null;
} {
    return value == TransactionType.buy ? {
        buy: null
    } : value == TransactionType.sell ? {
        sell: null
    } : value == TransactionType.stakingReward ? {
        stakingReward: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
